version: '3'

services:
  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    platform: linux/arm64/v8

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/quiz-time
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
    platform: linux/arm64/v8

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/quiz-time
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    restart: always
    platform: linux/arm64/v8

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    platform: linux/arm64/v8

volumes:
  db_data: {}
  wordpress_data: {} 